### ISSUE TITLE
システムスペック導入時のエラーについて

### ISSUE THREAD

**Issue by kapi819** [kapi819/portfolio_2#162]
- 解決したいもの(なるべく小さい粒度で記載してください)
　現在、本リリースに向けてCapybaraを使用したシステムスペックのコードを記載しているところ、実行時に、エラーが出ており、そのエラーを解決したく、質問します。

- エラー内容
　以下の通り、WebDriverが指定されたURLに接続できておらず、chromedriverへの接続が失敗している状況です。
```
docker compose run web bundle exec rspec              
[+] Building 0.0s (0/0)                                                                                                                                                                       docker:desktop-linux
[+] Creating 2/0
 ✔ Container portfolio_2-db-1      Running                                                                                                                                                                    0.0s 
 ✔ Container portfolio_2-chrome-1  Running                                                                                                                                                                    0.0s 
[+] Building 0.0s (0/0)                                                                                                                                                                       docker:desktop-linux

User
  add some examples to (or delete) /myapp/spec/models/user_spec.rb (PENDING: Not yet implemented)

Users
  Login処理
    LINEログインボタンを押した場合
2024-07-08 12:11:59 INFO Selenium [:logger_info] Details on how to use and modify Selenium logger:
  https://selenium.dev/documentation/webdriver/troubleshooting/logging

2024-07-08 12:11:59 WARN Selenium [DEPRECATION] DriverFinder.path(options, service_class) is deprecated. Use DriverFinder.new(options, service).driver_path instead.
      ログインができる (FAILED - 1)

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) User add some examples to (or delete) /myapp/spec/models/user_spec.rb
     # Not yet implemented
     # ./spec/models/user_spec.rb:4


Failures:

  1) Users Login処理 LINEログインボタンを押した場合 ログインができる
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: visit root_path
          
          Selenium::WebDriver::Error::WebDriverError:
            unable to connect to /root/.cache/selenium/chromedriver/linux64/126.0.6478.126/chromedriver 127.0.0.1:9515
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service_manager.rb:132:in `connect_until_stable'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service_manager.rb:58:in `block in start'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/socket_lock.rb:42:in `locked'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service_manager.rb:55:in `start'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service.rb:94:in `launch'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/driver.rb:322:in `service_url'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/local_driver.rb:28:in `initialize_local_driver'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/chrome/driver.rb:34:in `initialize'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver.rb:89:in `for'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/selenium/driver.rb:75:in `browser'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/session.rb:106:in `driver'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/session.rb:92:in `initialize'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara.rb:422:in `new'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara.rb:422:in `block in session_pool'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara.rb:317:in `current_session'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/dsl.rb:46:in `page'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/dsl.rb:52:in `visit'
          # ./spec/system/user_spec.rb:11:in `block (4 levels) in <top (required)>'

     1.2) Failure/Error: raise Error::WebDriverError, cannot_connect_error_text
          
          Selenium::WebDriver::Error::WebDriverError:
            unable to connect to /root/.cache/selenium/chromedriver/linux64/126.0.6478.126/chromedriver 127.0.0.1:9515
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service_manager.rb:132:in `connect_until_stable'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service_manager.rb:58:in `block in start'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/socket_lock.rb:42:in `locked'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service_manager.rb:55:in `start'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/service.rb:94:in `launch'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/driver.rb:322:in `service_url'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/local_driver.rb:28:in `initialize_local_driver'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/chrome/driver.rb:34:in `initialize'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/driver.rb:47:in `new'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver/common/driver.rb:47:in `for'
          # /usr/local/bundle/gems/selenium-webdriver-4.20.1/lib/selenium/webdriver.rb:89:in `for'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/selenium/driver.rb:75:in `browser'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/session.rb:106:in `driver'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/session.rb:92:in `initialize'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara.rb:422:in `new'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara.rb:422:in `block in session_pool'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara.rb:317:in `current_session'
          # /usr/local/bundle/gems/capybara-3.40.0/lib/capybara/dsl.rb:46:in `page'

Finished in 54.28 seconds (files took 1.8 seconds to load)
2 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/system/user_spec.rb:10 # Users Login処理 LINEログインボタンを押した場合 ログインができる

Coverage report generated for RSpec to /myapp/coverage. 138 / 178 LOC (77.53%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

- エラーの意味とエラー内容から推測される原因
　システムスペックを使用するため導入をしたネットワークが接続出来ない状況です。

- 実装する際に参考にした資料
　RUNTEQカリキュラム資料のrails/advancedのcapybara.rb、docker-compose.ymlの記載内容を参考にして作成しました。

- エラーを解決するために調べた資料
　接続が失敗している原因を探るため、Selenium Gridの状態を確認として、`docker-compose exec web curl -I http://chrome:4444/status`を実行しましたが、`HTTP/1.1 200 OK `と返しがあり、Selenium Gridのログを確認しても、エラーの記載がなく、エラーが発生する問題を特定し切れていません。

　最新のファイルは全てコミットしているところ、今回エラーが発生している原因をご教示していただければ幸いです。
　お忙しい中恐縮ですが、ご回答よろしくお願いします。

**Comment by kenchasonakai** [comment]
設定を行った現状のソースコードの共有もお願いします 🙏

**Comment by kapi819** [comment]
お手数お掛けしてしまい、申し訳ありません。
　本設定を行ったソースコードについては、既にmainブランチへマージしている状況なため、申し訳ありませんがDraft Pull Requestを作成出来ません。設定を行った現状のソースコードについて、以下に記載したのですが問題ないでしょうか。
　お手数お掛けしますが、ご確認よろしくお願いします。

.rspec
```
--require spec_helper
--format documentation
```

Gemfile（今回のエラー部分にかかる部分を抜粋）
```
group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]
  gem 'simplecov'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end
group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem 'launchy'
  gem "selenium-webdriver"
end
```

compose.yml
```
version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - my_network
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    networks:
      - my_network
  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 1g
    ports:
      - 4444:444
    networks:
      - my_network
volumes:
  bundle_data:
  postgresql_data:
  node_modules:
networks:
  my_network:
```

spec/rails_helper.rb
```
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
# Add additional requires below this line. Rails is not loaded until this point!

# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
#
# The following line is provided for convenience purposes. It has the downside
# of increasing the boot-up time by auto-requiring all files in the support
# directory. Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
Dir[Rails.root.join('spec', 'support', '**', '*.rb')].sort.each { |f| require f }

# Checks for pending migrations and applies them before tests are run.
# If you are not using ActiveRecord, you can remove these lines.
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  abort e.to_s.strip
end
RSpec.configure do |config|
  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_paths = [
    Rails.root.join('spec/fixtures')
  ]

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  config.use_transactional_fixtures = true

  # You can uncomment this line to turn off ActiveRecord support entirely.
  # config.use_active_record = false

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explicitly tag your specs with their type, e.g.:
  #
  #     RSpec.describe UsersController, type: :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://rspec.info/features/6-0/rspec-rails
  config.infer_spec_type_from_file_location!

  # FactoryBotの省略
  config.include FactoryBot::Syntax::Methods

  # Filter lines from Rails gems in backtraces.
  config.filter_rails_from_backtrace!
  # arbitrary gems may also be filtered via:
  # config.filter_gems_from_backtrace("gem name")
end
```

spec/spec_helper.rb（今回のエラーに関する初期ファイルの変更はしてないため参考）
```
require 'simplecov'
SimpleCov.start
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://rspec.info/features/3-12/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end
```

spec/ support/capybara.rb
```
require 'capybara/rspec'
require 'selenium/webdriver'

Capybara.register_driver :remote_chrome do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('no-sandbox')
  options.add_argument('headless')
  options.add_argument('disable-gpu')
  options.add_argument('window-size=1680,1050')
  Capybara::Selenium::Driver.new(app, browser: :remote, url: "http://chrome:4444/wd/hub", capabilities: options)
end

Capybara.javascript_driver = :remote_chrome

RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by :remote_chrome
    Capybara.ignore_hidden_elements = false
  end
end
```
spec/ support/omniauth.rb
```
OmniAuth.config.test_mode = true
# Line用のモック
OmniAuth.config.mock_auth[:line] = OmniAuth::AuthHash.new(
  provider: 'line', 
  uid: '12345', 
  info: { email: 'test1@example.com', name: 'test_user' },
  credentials: { token: '1234qwer' }
)
```

spec/system/user_spec.rb
```
require 'rails_helper'

RSpec.describe "Users", type: :system do
  describe 'Login処理' do
    before do
      Rails.application.env_config["devise.mapping"] = Devise.mappings[:user]
      Rails.application.env_config["omniauth.auth"] = OmniAuth.config.mock_auth[:line]
    end
    context 'LINEログインボタンを押した場合' do
      it 'ログインができる' do
        visit root_path
        click_on  'line_login'
        expect(page).to have_content '冷え性を改善するための目標を設定しましょう！'
      end
    end
  end
end
```

**Comment by kenchasonakai** [comment]
- `spec/support/`が`spec/ support`になっていてディレクトリ名に余計な空白が入っているので修正が必要そうです
- compose.ymlのnetworksの設定は不要かなと思います
- ファイルを以下のように変更してテストを実行してみてください

spec/support/capybara.rb
```
require 'capybara/rspec'
require 'selenium/webdriver'

Capybara.register_driver :remote_chrome do |app|
  options = Selenium::WebDriver::Chrome::Options.new
  options.add_argument('no-sandbox')
  options.add_argument('headless')
  options.add_argument('disable-gpu')
  options.add_argument('window-size=1680,1050')
  Capybara::Selenium::Driver.new(app, browser: :remote, url: "http://chrome:4444/wd/hub", capabilities: options)
end
```

spec/rails_helper.rb
```
# This file is copied to spec/ when you run 'rails generate rspec:install'
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require_relative '../config/environment'
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'
# Add additional requires below this line. Rails is not loaded until this point!

# Requires supporting ruby files with custom matchers and macros, etc, in
# spec/support/ and its subdirectories. Files matching `spec/**/*_spec.rb` are
# run as spec files by default. This means that files in spec/support that end
# in _spec.rb will both be required and run as specs, causing the specs to be
# run twice. It is recommended that you do not name files matching this glob to
# end with _spec.rb. You can configure this pattern with the --pattern
# option on the command line or in ~/.rspec, .rspec or `.rspec-local`.
#
# The following line is provided for convenience purposes. It has the downside
# of increasing the boot-up time by auto-requiring all files in the support
# directory. Alternatively, in the individual `*_spec.rb` files, manually
# require only the support files necessary.
#
Dir[Rails.root.join('spec', 'support', '**', '*.rb')].sort.each { |f| require f }

# Checks for pending migrations and applies them before tests are run.
# If you are not using ActiveRecord, you can remove these lines.
begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  abort e.to_s.strip
end
RSpec.configure do |config|
  # Remove this line if you're not using ActiveRecord or ActiveRecord fixtures
  config.fixture_paths = [
    Rails.root.join('spec/fixtures')
  ]

  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  config.use_transactional_fixtures = true

  # You can uncomment this line to turn off ActiveRecord support entirely.
  # config.use_active_record = false

  # RSpec Rails can automatically mix in different behaviours to your tests
  # based on their file location, for example enabling you to call `get` and
  # `post` in specs under `spec/controllers`.
  #
  # You can disable this behaviour by removing the line below, and instead
  # explicitly tag your specs with their type, e.g.:
  #
  #     RSpec.describe UsersController, type: :controller do
  #       # ...
  #     end
  #
  # The different available types are documented in the features, such as in
  # https://rspec.info/features/6-0/rspec-rails
  config.infer_spec_type_from_file_location!

  # FactoryBotの省略
  config.include FactoryBot::Syntax::Methods

  # Filter lines from Rails gems in backtraces.
  config.filter_rails_from_backtrace!
  # arbitrary gems may also be filtered via:
  # config.filter_gems_from_backtrace("gem name")

  config.before(:each, type: :system) do
    driven_by :remote_chrome
    Capybara.server_host = IPSocket.getaddress(Socket.gethostname)
    Capybara.server_port = 4444
    Capybara.app_host = "http://#{Capybara.server_host}:#{Capybara.server_port}"
    Capybara.ignore_hidden_elements = false
  end
end
```

**Comment by kapi819** [comment]
早急にご対応していただきいただきありがとうございます。
　ご教示していただいた内容をもとに修正して、テストを実行したところ、エラー無く実行出来ましたので、本ISSUEについてはCloseさせていただきます。
　誠にありがとうございました。
